version: "3.7"
services:
  backend:
    build: backend/
    env_file: ./.env
    restart: always
    volumes:
      - ./backend:/backend
      - ./externalVolumes/Coupons-Images:/backend/Coupons-Images
      - ./externalVolumes/Providers-Images:/backend/Providers-Images
      - ./externalVolumes/Categories-Images:/backend/Categories-Images
    ports:
      - "${COUPONAT_C_PORT}:${COUPONAT_N_PORT}"
    depends_on:
      - couponat-mongo-db
    networks:
      net:
  couponat-mongo-db:
    image: mongo:latest
    restart: always
    #ports:
    #  - "27019:27017"
    env_file: ./.env
    volumes:
      - mongo:/var/lib/mongo
      - ./externalVolumes/db:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    networks:
      net:
volumes:
  mongo:
networks:
  net:
    driver: bridge
