version: "3.7"
services:
  couponat-backend-2:
    image: couponat-backend-2
    build: .
    env_file: .env
    restart: always
    volumes:
      - ./Coupons-Images:/coupons/Coupons-Images
      - ./Providers-Images:/coupons/Providers-Images
      - ./Categories-Images:/coupons/Categories-Images
      - ./Subscriptions-Images:/coupons/Subscriptions-Images
      - ./Customers-Images:/coupons/Customers-Images
    ports:
      - "${COUPONAT_C_PORT}:${COUPONAT_N_PORT}"
    depends_on:
      - couponat-mongo-db-2
  couponat-mongo-db-2:
    image: "mongo"
    volumes:
      - ./mongo:/var/lib/mongo
      - ./externalVolumes/db:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
