version: "3.7"
services:
  backend:
    build: ./
    env_file: ./.env
    restart: always
    volumes:
      - ./externalVolumes/Clients-Images:/Users-Images
      - ./externalVolumes/Coupons-Images:/Coupons-Images
      - ./externalVolumes/Providers-Images:/Providers-Images
    ports:
      - "${COUPONAT_C_PORT}:${COUPONAT_N_PORT}"
    depends_on:
      - couponat-mongo-db
    networks:
      net:
  couponat-mongo-db:
    image: mongo:latest
    restart: always
    #ports:
    #  - "27018:27017"
    env_file: ./.env
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
    #   MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASS
    #   MONGO_INITDB_DATABASE: admin
    volumes:
      - mongo:/var/lib/mongo
      - ./externalVolumes/db:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    networks:
      net:
volumes:
  mongo:
networks:
  net:
    driver: bridge