version: "3.7"
services:
  couponat-backend-2:
    image: couponat-backend-2
    build: .
    env_file: .env
    restart: always
    volumes:
      - ./public/category-pictures
      - ./public/coupons
      - ./public/logos
      - ./public/payments
      - ./public/profile-pictures
    ports:
      - "${COUPONAT_C_PORT}:${COUPONAT_N_PORT}"
    depends_on:
      - couponat-mongo-db-2
  couponat-mongo-db-2:
    image: "mongo"
    volumes:
      - ./mongo:/var/lib/mongo
      - ./externalVolumes/db:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
