version: "3.7"
services:
  couponat-backend-2:
    build: ./
    env_file: ./.env
    restart: always
    volumes:
      - ./couponat-backend:/coupons/backend:delegated
      - ./externalVolumes/Coupons-Images:/coupons/Coupons-Images
      - ./externalVolumes/Providers-Images:/coupons/Providers-Images
      - ./externalVolumes/Categories-Images:/coupons/Categories-Images
      - ./externalVolumes/Subscriptions-Images:/coupons/Subscriptions-Images
      - ./externalVolumes/Customers-Images:/coupons/Customers-Images
    ports:
      - "${COUPONAT_C_PORT}:${COUPONAT_N_PORT}"
    depends_on:
      - couponat-mongo-db-2
  couponat-mongo-db-2:
    image: mongo:latest
    restart: always
    #ports:
    #  - "27019:27017"
    env_file: ./.env
    volumes:
      - ./mongo:/var/lib/mongo
      - ./externalVolumes/db:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
